---
openshift_login: false
openshift_username: ''
openshift_password: ''
openshift_token: ''
openshift_master_url: ''
eval_self_signed_certs: false

project_name: ''
project_display_name: ''
project_description: ''
