---

# https://access.redhat.com/RegistryAuthentication
- name: Generate Red Hat registry secret
  shell: |
      {{oc_cmd}} delete secret {{redhat_pull_secret_name}}
      {{oc_cmd}} create secret docker-registry {{redhat_pull_secret_name}} \
        --docker-server="https://registry.redhat.io" \
        --docker-username="{{ redhat_username }}" \
        --docker-password="{{ redhat_password }}" \
        --docker-email="{{ redhat_email }}"

- name: Link registry pull secret for default
  shell: |
    {{oc_cmd}} secrets link default {{redhat_pull_secret_name}}
    {{oc_cmd}} secrets link default {{redhat_pull_secret_name}} --for=pull

- name: Link registry pull secret for deployer
  shell: |
    {{oc_cmd}} secrets link deployer {{redhat_pull_secret_name}}
    {{oc_cmd}} secrets link deployer {{redhat_pull_secret_name}} --for=pull            

- name: Link registry pull secret for builder
  shell: | 
    {{oc_cmd}} secrets link builder {{redhat_pull_secret_name}}
    {{oc_cmd}} secrets link builder {{redhat_pull_secret_name}} --for=pull 
