---

- name: Check if project exists
  shell: "oc --context {{kube_ctx}} get project {{ project_name }}"
  register: project_check_result
  ignore_errors: true
  changed_when: false

- name: Create project
  shell: |
         oc --context {{kube_ctx}} new-project {{ project_name }} \
            --display-name="{{ project_display_name }}" \
            --description="{{ project_description }}"
  when: project_check_result is failed
