---

- name: Check if {{ project_name }} project exists
  shell: "oc --context {{kube_ctx}} get project {{ project_name }}"
  register: project_check_result
  ignore_errors: true
  changed_when: false

- name: Delete {{ project_name }} project
  shell: "oc --context {{kube_ctx}} delete project {{ project_name }} --wait=true"
  when: project_check_result is not failed

- name: Delete {{ project_name }} project
  shell: sleep 30
  when: project_check_result is not failed

## More to do to check the project is successfully deleted
