---

- name: Password authentication
  shell: |
    oc config delete-context {{kube_ctx}}
    oc login {{ openshift_master_url }} -u {{ openshift_username }} -p {{ openshift_password }} --insecure-skip-tls-verify={{ eval_self_signed_certs }}    
    oc config rename-context $(oc config current-context) {{kube_ctx}}
  when: openshift_password != ''

- name: Token authentication
  shell: | 
    oc config delete-context {{kube_ctx}}
    oc login {{ openshift_master_url }} --token {{ openshift_token }} --insecure-skip-tls-verify={{ eval_self_signed_certs }}
    oc config rename-context $(oc config current-context) {{kube_ctx}}
  when: openshift_token != ''
