---

- name: Ensure buildinput directory exists
  file:
    path: /tmp/buildinput/{{site_id}}
    state: directory

- name: Copy continuity.jar to /tmp
  copy:
    src: "{{ continuity_jar }}"
    dest: /tmp/buildinput/{{site_id}}/artemis-continuity-plugin.jar
    force: yes

- name: Copy configure-continuity.sh to /tmp
  copy:
    src: ../roles/amq7-broker/templates/artemis/configure-continuity.sh
    dest: /tmp/buildinput/{{site_id}}/configure-continuity.sh
    force: yes

- name: Copy launch.sh to /tmp 
  copy:
    src: ../roles/amq7-broker/templates/artemis/launch.sh
    dest: /tmp/buildinput/{{site_id}}/launch.sh
    force: yes

- name: Cleanup previous AMQ Continuity Image Build
  shell: |
    {{oc_cmd}} delete bc {{ continuity_image_name }} --ignore-not-found=true
    {{oc_cmd}} delete imagestream {{ continuity_image_name }}  --ignore-not-found=true 

- name: Generate build number
  set_fact:
    amq_continuity_version: "{{ amq_continuity_base_version }}.{{ 10000 | random }}"
  run_once: yes

- name: Create AMQ Continuity Image Build
  shell: |
    {{oc_cmd}} new-build --name={{ continuity_image_name }} --to="{{ continuity_image_name }}:{{ amq_continuity_version }}" \
      -D $'FROM registry.redhat.io/{{ amq_base_image }}:{{ amq_base_image_version }}\n \
            USER root\n \
            RUN mkdir -p /home/jboss/amq-broker/lib\n \
            COPY artemis-continuity-plugin.jar /home/jboss/amq-broker/lib/\n \
            RUN chown -R jboss:root /home/jboss/\n \
            RUN chmod -R a+rw /home/jboss/\n \
            RUN mv /opt/amq/bin/launch.sh /opt/amq/bin/amqlaunch.sh\n \
            COPY configure-continuity.sh /opt/amq/bin/configure-continuity.sh\n \
            COPY launch.sh /opt/amq/bin/launch.sh\n \
            RUN chown jboss:root /opt/amq/bin/amqlaunch.sh\n \
            RUN chown jboss:root /opt/amq/bin/configure-continuity.sh\n \
            RUN chown jboss:root /opt/amq/bin/launch.sh\n \
            RUN chmod 775 /opt/amq/bin/amqlaunch.sh\n \
            RUN chmod a+rx /opt/amq/bin/configure-continuity.sh\n \
            RUN chmod a+rx /opt/amq/bin/launch.sh\n'

- name: Start AMQ Continuity Image Build with build input supplied
  shell: |
    {{oc_cmd}} start-build {{ continuity_image_name }} --from-dir=/tmp/buildinput/{{site_id}} --wait --follow          




