---

- name: Ensure secret dirctory exists
  file:
    path: /tmp/{{site_id}}/{{secret_name}}
    state: directory
    
- name: Clean up previous keystore and truststore
  file:
    path: "/tmp/{{site_id}}/{{secret_name}}/{{ item }}"
    state: absent
  with_items:
    - broker.ks
    - broker_cert
    - client.ks
    - client.ts

- name: Generate broker keystore and truststore
  shell: |
    keytool -genkey -alias broker -keyalg RSA -keystore /tmp/{{site_id}}/{{secret_name}}/broker.ks -storepass "{{ keystore_pass }}" -dname "{{ sslstore_dname }}"
    keytool -export -alias broker -keystore /tmp/{{site_id}}/{{secret_name}}/broker.ks -file /tmp/{{site_id}}/{{secret_name}}/broker_cert -storepass "{{ keystore_pass }}"
    keytool -genkey -alias client -keyalg RSA -keystore /tmp/{{site_id}}/{{secret_name}}/client.ks -storepass "{{ truststore_pass }}" -dname "{{ sslstore_dname }}"
    keytool -import -alias broker -keystore /tmp/{{site_id}}/{{secret_name}}/client.ts -file /tmp/{{site_id}}/{{secret_name}}/broker_cert -storepass "{{ truststore_pass }}" -noprompt

- name: Generate Broker Secret
  shell: |     
    {{oc_cmd}} secrets new {{secret_name}} /tmp/{{site_id}}/{{secret_name}}/broker.ks /tmp/{{site_id}}/{{secret_name}}/client.ts
    
- name: Link Broker Secret to Operator Service Account
  shell: |     
    {{oc_cmd}} secrets link sa/amq-broker-operator secret/{{secret_name}}

