---

- hosts: sites
  gather_facts: yes
  tasks:

    - name: Delete project
      include_role:
        name: openshift
        tasks_from: delete-project.yml
      vars:
        project_name: "{{ continuity_project_name }}"
      when: do_create_project | default(true) | bool

    - name: Wait for Project to be deleted
      shell: sleep 30

    - name: Create project
      include_role:
        name: openshift
        tasks_from: create-project.yml
      vars:
        project_name: "{{ continuity_project_name }}"
        project_display_name: "AMQContinuity-{{ site_id }}"
        project_description: "AMQContinuity-{{ site_id }}"
      when: do_create_project | default(true) | bool 

  



